version: "3.5"

services:
  build:
    container_name: marlin-build
    image: frealmyr/docker-marlin-build:latest
    user: 1000:1000
    stdin_open: true
    tty: true
    environment:
      - BOARD
      # - UPDATE_SKIP=true # Skip update prompt
      # - UPDATE_FORCE=true # Update MarlinFirmware silently
    volumes:
      - $MARLIN_FIRMWARE:/home/platformio/build
      - $MARLIN_CONFIGURATION:/home/platformio/CustomConfiguration
      # - ./build-marlin.sh:/home/platformio/build-marlin.sh # Use build script in repo instead of image
